language: python 

os:
  - linux

branches:
  only:
    - master
    - /^(dev)|(dev_.*)$/

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - pytest -v
