os: Visual Studio 2015

version: 1.0.{build}

branches:
  only:
    - master

configuration:
  - Debug
  - Release

environment:
  matrix:
    - VS_VERSION: 14 2015
      VS_PLATFORM: win32
    - VS_VERSION: 14 2015
      VS_PLATFORM: x64

before_build:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio %VS_VERSION%" ..

build:
  project: build\Snake.sln
  parallel: true
  verbosity: minimal